#!/bin/bash
# makeMac
set -e; # halt on error
ODE_CFLAGS="-DdTRIMESH_ENABLED $(pkg-config ode --cflags)"
ODE_LIBS="$(pkg-config ode --libs)"
g++ $ODE_CFLAGS -c matrix.cpp       -o matrix.o
g++ $ODE_CFLAGS -c compassSensor.cpp       -o compassSensor.o
g++ $ODE_CFLAGS -c lightSensor.cpp       -o lightSensor.o
g++ $ODE_CFLAGS -c propSensor.cpp       -o propSensor.o
g++ $ODE_CFLAGS -c touchSensor.cpp       -o touchSensor.o
g++ $ODE_CFLAGS -c object.cpp       -o object.o
g++ $ODE_CFLAGS -c joint.cpp       -o joint.o
g++ $ODE_CFLAGS -c neuralNetwork.cpp       -o neuralNetwork.o
g++ $ODE_CFLAGS -c robot.cpp       -o robot.o
g++ $ODE_CFLAGS -c environment.cpp       -o environment.o
g++ $ODE_CFLAGS -c optimizer.cpp       -o optimizer.o
g++ $ODE_CFLAGS -c userModel.cpp       -o userModel.o
g++ $ODE_CFLAGS -c BackProp.cpp       -o BackProp.o
g++ $ODE_CFLAGS -c tauOptimizer.cpp       -o tauOptimizer.o
g++ $ODE_CFLAGS -c tau.cpp       -o tau.o
g++ $ODE_CFLAGS -c envs.cpp       -o envs.o
g++ $ODE_CFLAGS -c M3.cpp       -o M3.o

g++ -g -O2 -o M3 matrix.o compassSensor.o lightSensor.o propSensor.o touchSensor.o object.o joint.o neuralNetwork.o robot.o environment.o optimizer.o userModel.o BackProp.o tauOptimizer.o tau.o envs.o M3.o -Wl,-bind_at_load $ODE_LIBS -framework OpenGL -framework GLUT -lm -lpthread

